export const QUERY_KEY_ARTWORKS = "ARTWORKS";
export const QUERY_KEY_ARTWORKS_FILTERED = "ARTWORKS_FILTERED";
export const QUERY_KEY_ARTWORKS_FILTERED_BY_AGENT =
  "ARTWORKS_FILTERED_BY_AGENT";
export const QUERY_KEY_ARTWORK_DETAIL = "ARTWORK_DETAIL";
export const QUERY_KEY_AGENTS = "AGENTS";
export const QUERY_KEY_AGENTS_FILTERED = "AGENTS_FILTERED";
export const QUERY_KEY_AGENT_DETAIL = "AGENT_DETAIL";
