version: "3.9"

services:
  fontend:
    container_name: "frontend"
    image: art_gallery:1.3
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8000:8000
