import type { Meta, StoryObj } from "@storybook/react";

import { ArtworksTable } from "./ArtworksTable";

const meta = {
  title: "ui/Table/ArtworksTable",
  component: ArtworksTable,
  tags: ["autodocs"],
} satisfies Meta<typeof ArtworksTable>;

export default meta;

type Story = StoryObj<typeof meta>;

const artworks = [
  {
    id: 102472,
    title: "Oriental Theatre, Milwaukee, Wisconsin",
    thumbnail: {
      lqip: "data:image/gif;base64,R0lGODlhBAAFAPQAAB4jKiYnLzQqMDo6PFIxNT89QUFBRkhESElFSU1ISnJKSWNZVXxUUolOTIlSTIpiWJdyXKZ1VaB0XI1waAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAAAAAAALAAAAAAEAAUAAAUR4HIUCRIAgyEQCtM4zyRFUAgAOw==",
      width: 2406,
      height: 3000,
      alt_text: "A work made of chromogenic print.",
    },
    date_display: "1983",
    artist_display: "Don A. DuBroff\nAmerican, born 1951",
    place_of_origin: "United States",
    description: null,
    short_description: null,
    dimensions:
      "Image: 48.1 × 38 cm (18 15/16 × 15 in.); Paper: 50.7 × 40.6 cm (20 × 16 in.)",
    medium_display: "Chromogenic print",
    catalogue_display: null,
    publication_history: null,
    artwork_type_title: "Photograph",
    artist_id: 30979,
    artist_title: "Don A. DuBroff",
    image_id: "acebe62e-e7d2-b1bf-49bc-dc0324b16dde",
  },
  {
    id: 102471,
    title: "Oriental Theatre, Milwaukee, Wisconsin",
    thumbnail: {
      lqip: "data:image/gif;base64,R0lGODlhBAAFAPQAAB4jKiYnLzQqMDo6PFIxNT89QUFBRkhESElFSU1ISnJKSWNZVXxUUolOTIlSTIpiWJdyXKZ1VaB0XI1waAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAAAAAAALAAAAAAEAAUAAAUR4HIUCRIAgyEQCtM4zyRFUAgAOw==",
      width: 2406,
      height: 3000,
      alt_text: "A work made of chromogenic print.",
    },
    date_display: "1983",
    artist_display: "Don A. DuBroff\nAmerican, born 1951",
    place_of_origin: "United States",
    description: null,
    short_description: null,
    dimensions:
      "Image: 48.1 × 38 cm (18 15/16 × 15 in.); Paper: 50.7 × 40.6 cm (20 × 16 in.)",
    medium_display: "Chromogenic print",
    catalogue_display: null,
    publication_history: null,
    artwork_type_title: "Photograph",
    artist_id: 30979,
    artist_title: "Don A. DuBroff",
    image_id: "acebe62e-e7d2-b1bf-49bc-dc0324b16dde",
  },
  {
    id: 102470,
    title: "Our Lady of Sorrows Basilica, Chicago",
    thumbnail: {
      lqip: "data:image/gif;base64,R0lGODlhBgAFAPQAAFlUS2ddVGRiVm1kWn1nVX5mWHJoX2lsam97fXJyc39/foBuVoRpWYRtXYZ1W4BwX4JybYJ4bJV9YYd4dYp7cYF4eJSBc5+Kc5aNe5mOfaCLa6OLdMCZbsKdcgAAAAAAACH5BAAAAAAALAAAAAAGAAUAAAUYoAJNVYJQBdMYh0UEwxNtwOIIVyZxnYaFADs=",
      width: 3000,
      height: 2384,
      alt_text: "A work made of chromogenic print.",
    },
    date_display: "1981",
    artist_display: "Don A. DuBroff\nAmerican, born 1951",
    place_of_origin: "United States",
    description: null,
    short_description: null,
    dimensions:
      "Image: 38 × 48.2 cm (15 × 19 in.); Paper: 40.6 × 50.7 cm (16 × 20 in.)",
    medium_display: "Chromogenic print",
    catalogue_display: null,
    publication_history: null,
    artwork_type_title: "Photograph",
    artist_id: 30979,
    artist_title: "Don A. DuBroff",
    image_id: "99837c39-af9d-a080-63c0-b34268f41674",
  },
  {
    id: 102469,
    title: "Our Lady of Sorrows Basilica, Chicago",
    thumbnail: {
      lqip: "data:image/gif;base64,R0lGODlhBgAFAPQAAFlUS2ddVGRiVm1kWn1nVX5mWHJoX2lsam97fXJyc39/foBuVoRpWYRtXYZ1W4BwX4JybYJ4bJV9YYd4dYp7cYF4eJSBc5+Kc5aNe5mOfaCLa6OLdMCZbsKdcgAAAAAAACH5BAAAAAAALAAAAAAGAAUAAAUYoAJNVYJQBdMYh0UEwxNtwOIIVyZxnYaFADs=",
      width: 3000,
      height: 2384,
      alt_text: "A work made of chromogenic print.",
    },
    date_display: "1981",
    artist_display: "Don A. DuBroff\nAmerican, born 1951",
    place_of_origin: "United States",
    description: null,
    short_description: null,
    dimensions:
      "Image: 38 × 48.2 cm (15 × 19 in.); Paper: 40.6 × 50.7 cm (16 × 20 in.)",
    medium_display: "Chromogenic print",
    catalogue_display: null,
    publication_history: null,
    artwork_type_title: "Photograph",
    artist_id: 30979,
    artist_title: "Don A. DuBroff",
    image_id: "99837c39-af9d-a080-63c0-b34268f41674",
  },
  {
    id: 102468,
    title: "Notre Dame Church, Chicago",
    thumbnail: {
      lqip: "data:image/gif;base64,R0lGODlhBAAFAPQAAGpTP3lWMnhWM3lZMVpOR15RRl1idJReJ49fMJZnLY9iNJFuP6FxLaBxN6x9S5V8Y6ODYnF3gFeBrnaHxwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAAAAAAALAAAAAAEAAUAAAUR4OI0ADRFySMZCoMcQTEIRAgAOw==",
      width: 2406,
      height: 3000,
      alt_text: "A work made of chromogenic print.",
    },
    date_display: "1983",
    artist_display: "Don A. DuBroff\nAmerican, born 1951",
    place_of_origin: "United States",
    description: null,
    short_description: null,
    dimensions:
      "Image: 48.1 × 38 cm (18 15/16 × 15 in.); Paper: 50.7 × 40.6 cm (20 × 16 in.)",
    medium_display: "Chromogenic print",
    catalogue_display: null,
    publication_history: null,
    artwork_type_title: "Photograph",
    artist_id: 30979,
    artist_title: "Don A. DuBroff",
    image_id: "99ceb6af-1f61-9911-9bda-8d8ac1ac3db4",
  },
  {
    id: 102467,
    title: "Notre Dame Church, Chicago",
    thumbnail: {
      lqip: "data:image/gif;base64,R0lGODlhBAAFAPQAAGpTP3lWMnhWM3lZMVpOR15RRl1idJReJ49fMJZnLY9iNJFuP6FxLaBxN6x9S5V8Y6ODYnF3gFeBrnaHxwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAAAAAAALAAAAAAEAAUAAAUR4OI0ADRFySMZCoMcQTEIRAgAOw==",
      width: 2406,
      height: 3000,
      alt_text: "A work made of chromogenic print.",
    },
    date_display: "1983",
    artist_display: "Don A. DuBroff\nAmerican, born 1951",
    place_of_origin: "United States",
    description: null,
    short_description: null,
    dimensions:
      "Image: 48.1 × 38.1 cm (18 15/16 × 15 in.); Paper: 50.7 × 40.6 cm (20 × 16 in.)",
    medium_display: "Chromogenic print",
    catalogue_display: null,
    publication_history: null,
    artwork_type_title: "Photograph",
    artist_id: 30979,
    artist_title: "Don A. DuBroff",
    image_id: "99ceb6af-1f61-9911-9bda-8d8ac1ac3db4",
  },
  {
    id: 102466,
    title: "St. Nicolas Ukrainian Cathedral, Chicago",
    thumbnail: {
      lqip: "data:image/gif;base64,R0lGODlhBAAFAPQAADAwMzhVVk1GQFtVTmtjVVlrc099fGltcINuYot7bqeEZF12iUp1kVZ/l06JhmeVjGiBkFSvqo+XlaikowAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAAAAAAALAAAAAAEAAUAAAURICAEzkA8UaIgxiQVx8I0UAgAOw==",
      width: 642,
      height: 768,
      alt_text: "A work made of chromogenic print.",
    },
    date_display: "1979",
    artist_display: "Don A. DuBroff\nAmerican, born 1951",
    place_of_origin: "United States",
    description: null,
    short_description: null,
    dimensions:
      "Image: 45.3 × 38.1 cm (17 7/8 × 15 in.); Paper: 50.7 × 40.6 cm (20 × 16 in.)",
    medium_display: "Chromogenic print",
    catalogue_display: null,
    publication_history: null,
    artwork_type_title: "Photograph",
    artist_id: 30979,
    artist_title: "Don A. DuBroff",
    image_id: "11834aed-2bf6-dc5c-4481-3436a1a2c0d4",
  },
  {
    id: 102465,
    title: "St. Nicolas Ukrainian Cathedral, Chicago",
    thumbnail: {
      lqip: "data:image/gif;base64,R0lGODlhBAAFAPQAAC1GUjNNVR5RaSddZChVaBZtejBiazpsc1NPT1tRSktXXFNXXWBXU2liXUdfZ0xmd1Focot0X46Ben6CigAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAAAAAAALAAAAAAEAAUAAAUR4IIER5MMhRQxxgQByiMQTggAOw==",
      width: 2538,
      height: 3000,
      alt_text: "A work made of chromogenic print.",
    },
    date_display: "1979",
    artist_display: "Don A. DuBroff\nAmerican, born 1951",
    place_of_origin: "United States",
    description: null,
    short_description: null,
    dimensions:
      "Image: 45.3 × 38 cm (17 7/8 × 15 in.); Paper: 50.7 × 40.6 cm (20 × 16 in.)",
    medium_display: "Chromogenic print",
    catalogue_display: null,
    publication_history: null,
    artwork_type_title: "Photograph",
    artist_id: 30979,
    artist_title: "Don A. DuBroff",
    image_id: "5d647f14-1c0d-2469-5241-c926d380baf8",
  },
  {
    id: 207100,
    title:
      "Untitled, from Portfolio from the School of the Art Institute of Chicago",
    thumbnail: {
      lqip: "data:image/gif;base64,R0lGODlhBAAFAPQAABQoLBotMTpJTTtLTkNRVEVUVsLHxcPHxsjNy83R0NDU0tve29vd3OLk4u/w7PX08vb18/z7+P38+gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAAAAAAALAAAAAAEAAUAAAURoLM0D1IMihEAySEQDCRJUQgAOw==",
      width: 2305,
      height: 3000,
      alt_text:
        "A work made of screenprint in black, over greenish blue, on white wove paper.",
    },
    date_display: "1969",
    artist_display: "Ed Paschke\nAmerican, 1939-2004",
    place_of_origin: "United States",
    description: null,
    short_description: null,
    dimensions:
      "Image: 34.8 × 27.2 cm (13 3/4 × 10 3/4 in.); Sheet: 58.4 × 44.4 cm (23 × 17 1/2 in.)",
    medium_display:
      "Screenprint in black, over greenish blue, on white wove paper",
    catalogue_display: "<p>Adrian and Born 229</p>",
    publication_history: null,
    artwork_type_title: "Print",
    artist_id: 36138,
    artist_title: "Ed Paschke",
    image_id: "6d99b5ec-3e16-d1b1-f843-3cf46bae3cd1",
  },
  {
    id: 200136,
    title: "Frankie",
    thumbnail: {
      lqip: "data:image/gif;base64,R0lGODlhBAAFAPQAAKKgmqimoKmmoK2rpbe1rrm3sL66tL+8tcPBucvHwMzKws3Kw9DOxtXSytfVzdnWzeHe1uPf2OPg2Ofl3QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAAAAAAALAAAAAAEAAUAAAURYJQcjWQEziIAxUMMyMQoUAgAOw==",
      width: 5349,
      height: 6993,
      alt_text: "A work made of graphite on ivory wove paper.",
    },
    date_display: "1974",
    artist_display: "Ed Paschke\nAmerican, 1939-2004",
    place_of_origin: "United States",
    description: null,
    short_description: null,
    dimensions: "45.7 × 61 cm (18 × 24 1/16 in.)",
    medium_display: "Graphite on ivory wove paper",
    catalogue_display: null,
    publication_history: null,
    artwork_type_title: "Drawing and Watercolor",
    artist_id: 36138,
    artist_title: "Ed Paschke",
    image_id: "e9c6b89a-aa96-7031-a6e6-0dc8d86ab109",
  },
];

export const Default: Story = {
  args: {
    artworks: artworks,
  },
};
