/* import * as ReactQuery from "@tanstack/react-query"; */
import { render, screen } from "@testing-library/react";
import { AgentDetail } from "./AgentDetail";
import "@testing-library/jest-dom";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

const MockData = {
  pagination: {
    total: 126065,
    limit: 12,
    offset: 0,
    total_pages: 10506,
    current_page: 1,
    next_url: "https://api.artic.edu/api/v1/artworks?page=2",
  },
  data: [
    {
      id: 214932,
      api_model: "artworks",
      api_link: "https://api.artic.edu/api/v1/artworks/214932",
      is_boosted: false,
      title: "One Inch to a Foot",
      alt_titles: null,
      thumbnail: {
        lqip: "data:image/gif;base64,R0lGODlhAwAFAPMAAHdcR3hcSG9dUoR1a4p4aop4a5qSiZ6VjqCYkqefmaihm6ignKihnaqjn6yloQAAACH5BAAAAAAALAAAAAADAAUAAAQLEB3TVmJOlUGCABEAOw==",
        width: 1531,
        height: 2277,
        alt_text:
          "A work made of overhead projector, photo-negative glass plate.",
      },
      main_reference_number: "2013.48a-b",
      has_not_been_viewed_much: false,
      boost_rank: null,
      date_start: 1971,
      date_end: 1971,
      date_display: "1971",
      date_qualifier_title: "",
      date_qualifier_id: null,
      artist_display: "John Knight\nAmerican, born 1945",
      place_of_origin: "United States",
      description:
        "<p>Since the late 1960s, John Knight has addressed the ideologies of built and designed space, often through existing systems of visual communication not generally associated with art making. The title phrase of his important early work <em>One Inch to a Foot</em> makes obvious reference to scale notations on architectural plans. It is etched in one-inch high, Helvetica letters on the plate of a standard overhead projector; once projected, each letter measures one foot in height. Thus a representational convention of architectural plans is physically enacted, and the work carves out real space as well: the projector requires 15 feet of distance from the wall in order to execute the title statement. <em>One Inch to a Foot</em> is technically portable but always establishes a direct relationship to its site of installation.</p>\n",
      short_description: null,
      dimensions:
        "67.3 × 33 × 33 × 365.8 cm (26 ½ × 13 × 13 × 144 in.), installed",
      dimensions_detail: [],
      medium_display: "Overhead projector, photo-negative glass plate",
      inscriptions: null,
      credit_line:
        "Through prior purchase with funds provided by Mr. and Mrs. Solomon B. Smith;  Watson F. Blair Prize and Mr. and Mrs. Frank G. Logan Purchase Prize Fund;  purchased with funds provided by Dorie Sternberg; Emilie L. Wild Prize Fund; Contemporary Art Discretionary Fund; through the generosity of Carol Greene",
      catalogue_display: null,
      publication_history: null,
      exhibition_history: null,
      provenance_text: null,
      edition: null,
      publishing_verification_level: "Web Basic",
      internal_department_id: 246,
      fiscal_year: 2013,
      fiscal_year_deaccession: null,
      is_public_domain: false,
      is_zoomable: true,
      max_zoom_window_size: 1280,
      copyright_notice: "© 1971 John Knight",
      has_multimedia_resources: false,
      has_educational_resources: false,
      has_advanced_imaging: false,
      colorfulness: 18.6723,
      color: {
        h: 217,
        l: 55,
        s: 20,
        percentage: 0.000283789382871608,
        population: 3,
      },
      latitude: null,
      longitude: null,
      latlon: null,
      is_on_view: false,
      on_loan_display: null,
      gallery_title: null,
      gallery_id: null,
      nomisma_id: null,
      artwork_type_title: "Installation",
      artwork_type_id: 16,
      department_title: "Contemporary Art",
      department_id: "PC-8",
      artist_id: 31731,
      artist_title: "John Knight",
      alt_artist_ids: [],
      artist_ids: [31731],
      artist_titles: ["John Knight"],
      category_ids: ["PC-8"],
      category_titles: ["Contemporary Art"],
      term_titles: ["installation", "glass"],
      style_id: null,
      style_title: null,
      alt_style_ids: [],
      style_ids: [],
      style_titles: [],
      classification_id: "TM-1152",
      classification_title: "installation",
      alt_classification_ids: [],
      classification_ids: ["TM-1152"],
      classification_titles: ["installation"],
      subject_id: null,
      alt_subject_ids: [],
      subject_ids: [],
      subject_titles: [],
      material_id: "TM-2453",
      alt_material_ids: [],
      material_ids: ["TM-2453"],
      material_titles: ["glass"],
      technique_id: null,
      alt_technique_ids: [],
      technique_ids: [],
      technique_titles: [],
      theme_titles: [],
      image_id: "9e798f3f-e42b-b844-d81a-f9c0266dd5c7",
      alt_image_ids: [],
      document_ids: [],
      sound_ids: [],
      video_ids: [],
      text_ids: [],
      section_ids: [],
      section_titles: [],
      site_ids: [],
      suggest_autocomplete_all: [
        {
          input: ["2013.48a-b"],
          contexts: {
            groupings: ["accession"],
          },
        },
        {
          input: ["One Inch to a Foot"],
          weight: 541,
          contexts: {
            groupings: ["title"],
          },
        },
      ],
      source_updated_at: "2024-08-08T17:08:11-05:00",
      updated_at: "2024-08-08T17:10:20-05:00",
      timestamp: "2024-08-08T20:30:30-05:00",
    },
    {
      id: 43081,
      api_model: "artworks",
      api_link: "https://api.artic.edu/api/v1/artworks/43081",
      is_boosted: false,
      title: "Fragment (Skirt)",
      alt_titles: null,
      thumbnail: {
        lqip: "data:image/gif;base64,R0lGODlhAgAFAPMAADc3OEA/QHNycoqJiZCQkJOTk62srLe3tri3t8LCwgAAAAAAAAAAAAAAAAAAAAAAACH5BAAAAAAALAAAAAACAAUAAAQIUAyDTiIlgAgAOw==",
        width: 353,
        height: 937,
        alt_text:
          'A work made of cotton, mixed lace: bobbin part lace of a type known as "duchesse" and needle lace of a type known as "point de gaze" with later addition of silk, machine twist net.',
      },
      main_reference_number: "1941.969",
      has_not_been_viewed_much: true,
      boost_rank: null,
      date_start: 1875,
      date_end: 1900,
      date_display: "1875/1900",
      date_qualifier_title: "Made",
      date_qualifier_id: 4,
      artist_display:
        "Designed by Bertha Honoré Palmer (American, 1850–1918)\nBelgium, Brussels",
      place_of_origin: "Brussels",
      description: null,
      short_description: null,
      dimensions: "143.5 × 167.7 cm (56 1/2 × 66 in.)",
      dimensions_detail: [
        {
          depth: null,
          width: 167,
          height: 143,
          diameter: null,
          clarification: null,
        },
      ],
      medium_display:
        'Cotton, mixed lace: bobbin part lace of a type known as "Duchesse" and needle lace of a type known as "Point de Gaze" with later addition of silk, machine twist net',
      inscriptions: null,
      credit_line:
        "Gift of Princess Cantacuzene in memory of Mrs. Potter Palmer I",
      catalogue_display: null,
      publication_history: null,
      exhibition_history: null,
      provenance_text: null,
      edition: null,
      publishing_verification_level: "Web Basic",
      internal_department_id: 4,
      fiscal_year: null,
      fiscal_year_deaccession: null,
      is_public_domain: true,
      is_zoomable: true,
      max_zoom_window_size: -1,
      copyright_notice: null,
      has_multimedia_resources: false,
      has_educational_resources: false,
      has_advanced_imaging: false,
      colorfulness: 3.8601,
      color: {
        h: 39,
        l: 53,
        s: 0,
        percentage: 0.020777744915017965,
        population: 392,
      },
      latitude: null,
      longitude: null,
      latlon: null,
      is_on_view: false,
      on_loan_display: null,
      gallery_title: null,
      gallery_id: null,
      nomisma_id: null,
      artwork_type_title: "Textile",
      artwork_type_id: 5,
      department_title: "Textiles",
      department_id: "PC-14",
      artist_id: 45087,
      artist_title: "Bertha Honoré Palmer, (Mrs. Potter Palmer, I)",
      alt_artist_ids: [],
      artist_ids: [45087],
      artist_titles: ["Bertha Honoré Palmer, (Mrs. Potter Palmer, I)"],
      category_ids: ["PC-14", "PC-825"],
      category_titles: ["Textiles", "Women artists"],
      term_titles: [
        "flowers",
        "lace making",
        "cotton (textile)",
        "textile",
        "lace - mixed",
        "white (color)",
        "medallions",
        "silk (textile)",
        "net (textile)",
        "needle lace",
        "duchesse lace",
        "costume",
        "bobbin lace",
        "dress (garment)",
        "skirt (garment)",
      ],
      style_id: null,
      style_title: null,
      alt_style_ids: [],
      style_ids: [],
      style_titles: [],
      classification_id: "TM-69",
      classification_title: "textile",
      alt_classification_ids: [
        "TM-1661",
        "TM-11901",
        "TM-11900",
        "TM-81",
        "TM-11899",
        "TM-11897",
        "TM-11752",
      ],
      classification_ids: [
        "TM-69",
        "TM-1661",
        "TM-11901",
        "TM-11900",
        "TM-81",
        "TM-11899",
        "TM-11897",
        "TM-11752",
      ],
      classification_titles: [
        "textile",
        "lace - mixed",
        "needle lace",
        "duchesse lace",
        "costume",
        "bobbin lace",
        "dress (garment)",
        "skirt (garment)",
      ],
      subject_id: "TM-10482",
      alt_subject_ids: ["TM-11841", "TM-11227"],
      subject_ids: ["TM-10482", "TM-11841", "TM-11227"],
      subject_titles: ["flowers", "white (color)", "medallions"],
      material_id: "TM-2578",
      alt_material_ids: ["TM-2579", "TM-3158"],
      material_ids: ["TM-2578", "TM-2579", "TM-3158"],
      material_titles: ["cotton (textile)", "silk (textile)", "net (textile)"],
      technique_id: "TM-4211",
      alt_technique_ids: [],
      technique_ids: ["TM-4211"],
      technique_titles: ["lace making"],
      theme_titles: ["Women artists"],
      image_id: "05792838-1f37-0481-688f-2633bffe3c34",
      alt_image_ids: [],
      document_ids: [],
      sound_ids: [],
      video_ids: [],
      text_ids: [],
      section_ids: [],
      section_titles: [],
      site_ids: [],
      suggest_autocomplete_all: [
        {
          input: ["1941.969"],
          contexts: {
            groupings: ["accession"],
          },
        },
        {
          input: ["Fragment (Skirt)"],
          weight: 82,
          contexts: {
            groupings: ["title"],
          },
        },
      ],
      source_updated_at: "2024-08-08T17:01:44-05:00",
      updated_at: "2024-08-08T17:05:22-05:00",
      timestamp: "2024-08-08T20:30:30-05:00",
    },
    {
      id: 80570,
      api_model: "artworks",
      api_link: "https://api.artic.edu/api/v1/artworks/80570",
      is_boosted: false,
      title: "Saints Apollonia, Barbara, and Agatha",
      alt_titles: null,
      thumbnail: {
        lqip: "data:image/gif;base64,R0lGODlhCgAFAPUAAEYvHFM7HEszIko2Jk44IEs+KFg2IlE5IlM8IUhALVlDJ1pGJ1VBKlZAK1dCL1lDKFNEM1JHM19JNF9MNF9ONmtAKWVNK2JOLmhMLWpSKnpcL2NNNWlPNWdRMWdRMmZSM2lRM2lTNG5YNm9aOH1iPmpVQGdYQmpaRG9dRnNeQn5mToVoOYRfQIFnQoJqRYpxSo50S5B0SgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAAAAAAALAAAAAAKAAUAAAYuwAPhAfKERJeFAoEhdVywUaxlCXBSGpZq9UJlAIOEoWL6RCAFgaThKJ0okw0jCAA7",
        width: 7088,
        height: 3469,
        alt_text: "A work made of tempera on panel.",
      },
      main_reference_number: "1954.307",
      has_not_been_viewed_much: false,
      boost_rank: null,
      date_start: 1475,
      date_end: 1500,
      date_display: "1490/1500",
      date_qualifier_title: "",
      date_qualifier_id: null,
      artist_display: "Master Alejo (Alejo Andía?; active Spain, c. 1485–1516)",
      place_of_origin: "Spain",
      description: null,
      short_description: null,
      dimensions:
        "56.5 × 122 cm (22 1/4 × 48 in.); Painted surface Saint Apollonia: 41 × 36 cm (16 1/8 × 14 1/8 in.); Saint Barbara: 40.5 × 36 cm (15 7/8 × 14 1/8 in.); Saint Agatha: 40.5 × 36 cm (15 7/8 × 14 1/8 in.)",
      dimensions_detail: [
        {
          depth: null,
          width: 122,
          height: 56,
          diameter: null,
          clarification: null,
        },
        {
          depth: null,
          width: 36,
          height: 41,
          diameter: null,
          clarification: "Painted surface Saint Apollonia",
        },
        {
          depth: null,
          width: 36,
          height: 40,
          diameter: null,
          clarification: "Saint Barbara",
        },
        {
          depth: null,
          width: 36,
          height: 40,
          diameter: null,
          clarification: "Saint Agatha",
        },
      ],
      medium_display: "Tempera on panel",
      inscriptions: null,
      credit_line: "Gift of Joseph Winterbotham",
      catalogue_display: null,
      publication_history:
        "Chandler Rathfon Post, A History of Spanish Painting vol. 9, pt. 1 (Cambridge, MA: Harvard University Press, 1947), 488, fig. 182A. \n\nUlrich Thieme and Felix Becker, Allgemeines Lexikon der bildenden Künstler von der Antike bis zur Gegenwart, vol. 37 (Leipzig: E.A. Seemann, 1950), 314. \n\nJudith Berg Sobre, Behind the Altar Table: The development of the Painted retable in Spain, 1350-1500 (Columbia: University of Missouri Press, 1989), 52.\n\nMaría Pilar Silva Maroto, Pintura hispanoflamenca castellana: Burgos y Palencia vol. 3, ([Valladolid]: Junta de Castilla y Leon, 1990), 953–55, nos. 33–35, fig. 380.",
      exhibition_history:
        "Arts Club of Chicago, Exhibition of the Joseph Winterbotham Collection, Dec. 9-31, 1936, cat. 7.",
      provenance_text:
        "Parish church of San Andrés, Villamediana (Palencia) [based on their relation to paintings presumably from the same retable still in San Andrés]. Galerie Heinemann, Munich, probably by 1926 [this date is suggested by a paper label imprinted Galerie Heinemann, Munchen / 18734, and a customs label reading ZOLL / I-26]; sold to Joseph Winterbotham, Jr. (died 1954), Burlington, Vt., by 1936 [lent by him to the 1936 exhibition; an annotated list of loans gives Heinemann as the source for the picture; Silva Maroto 1990 stated that it was in the Winterbotham collection in 1933]; bequeathed to the Art Institute, 1954.",
      edition: null,
      publishing_verification_level: "Web Cataloged",
      internal_department_id: 14,
      fiscal_year: 1955,
      fiscal_year_deaccession: null,
      is_public_domain: true,
      is_zoomable: true,
      max_zoom_window_size: -1,
      copyright_notice: null,
      has_multimedia_resources: false,
      has_educational_resources: false,
      has_advanced_imaging: false,
      colorfulness: 41.4263,
      color: {
        h: 38,
        l: 50,
        s: 57,
        percentage: 0.01641156756383236,
        population: 57,
      },
      latitude: null,
      longitude: null,
      latlon: null,
      is_on_view: false,
      on_loan_display: null,
      gallery_title: null,
      gallery_id: null,
      nomisma_id: null,
      artwork_type_title: "Painting",
      artwork_type_id: 1,
      department_title: "Painting and Sculpture of Europe",
      department_id: "PC-10",
      artist_id: 108377,
      artist_title: "Master Alejo (Alejo Andía?)",
      alt_artist_ids: [],
      artist_ids: [108377],
      artist_titles: ["Master Alejo (Alejo Andía?)"],
      category_ids: ["PC-10"],
      category_titles: ["Painting and Sculpture of Europe"],
      term_titles: [
        "tempera",
        "painting",
        "15th century",
        "saints",
        "painting",
        "tempera",
        "religion",
        "painting",
        "panel (wood)",
        "panel painting",
        "Renaissance",
        "religious",
        "religious figures",
        "Christianity",
        "Christian subjects",
        "painting techniques",
        "painting (image making)",
        "wood (plant material)",
        "plant material",
        "paint",
        "organic material",
        "spanish",
        "paint",
        "woman",
        "women",
        "gold (color)",
        "palm",
        "tower",
        "crowns",
        "plates",
        "martyrs",
        "Frame",
        "blue (color)",
        "red (color)",
        "jewelry",
        "Devotion",
        "european painting",
      ],
      style_id: "TM-14074",
      style_title: "15th century",
      alt_style_ids: ["TM-5891"],
      style_ids: ["TM-14074", "TM-5891"],
      style_titles: ["15th century", "Renaissance"],
      classification_id: "TM-9",
      classification_title: "painting",
      alt_classification_ids: ["TM-153", "TM-15664", "TM-10387", "TM-54"],
      classification_ids: ["TM-9", "TM-153", "TM-15664", "TM-10387", "TM-54"],
      classification_titles: [
        "painting",
        "tempera",
        "spanish",
        "paint",
        "european painting",
      ],
      subject_id: "TM-8827",
      alt_subject_ids: [
        "TM-11421",
        "TM-14384",
        "TM-12554",
        "TM-12372",
        "TM-8767",
        "TM-13813",
        "TM-8735",
        "TM-11859",
        "TM-15075",
        "TM-14924",
        "TM-8778",
        "TM-12744",
        "TM-9204",
        "TM-15532",
        "TM-11843",
        "TM-11851",
        "TM-12623",
        "TM-14366",
      ],
      subject_ids: [
        "TM-8827",
        "TM-11421",
        "TM-14384",
        "TM-12554",
        "TM-12372",
        "TM-8767",
        "TM-13813",
        "TM-8735",
        "TM-11859",
        "TM-15075",
        "TM-14924",
        "TM-8778",
        "TM-12744",
        "TM-9204",
        "TM-15532",
        "TM-11843",
        "TM-11851",
        "TM-12623",
        "TM-14366",
      ],
      subject_titles: [
        "saints",
        "religion",
        "religious",
        "religious figures",
        "Christianity",
        "Christian subjects",
        "woman",
        "women",
        "gold (color)",
        "palm",
        "tower",
        "crowns",
        "plates",
        "martyrs",
        "Frame",
        "blue (color)",
        "red (color)",
        "jewelry",
        "Devotion",
      ],
      material_id: "TM-2405",
      alt_material_ids: [
        "TM-13502",
        "TM-3644",
        "TM-2431",
        "TM-3478",
        "TM-2577",
        "TM-2601",
      ],
      material_ids: [
        "TM-2405",
        "TM-13502",
        "TM-3644",
        "TM-2431",
        "TM-3478",
        "TM-2577",
        "TM-2601",
      ],
      material_titles: [
        "tempera",
        "painting",
        "panel (wood)",
        "wood (plant material)",
        "plant material",
        "paint",
        "organic material",
      ],
      technique_id: "TM-14210",
      alt_technique_ids: ["TM-3975", "TM-3971", "TM-3891"],
      technique_ids: ["TM-14210", "TM-3975", "TM-3971", "TM-3891"],
      technique_titles: [
        "painting",
        "panel painting",
        "painting techniques",
        "painting (image making)",
      ],
      theme_titles: [],
      image_id: "03bdfb47-020e-7108-5a72-81a73b58dac9",
      alt_image_ids: [],
      document_ids: [],
      sound_ids: [],
      video_ids: [],
      text_ids: [],
      section_ids: [],
      section_titles: [],
      site_ids: [],
      suggest_autocomplete_all: [
        {
          input: ["1954.307"],
          contexts: {
            groupings: ["accession"],
          },
        },
        {
          input: ["Saints Apollonia, Barbara, and Agatha"],
          weight: 321,
          contexts: {
            groupings: ["title"],
          },
        },
      ],
      source_updated_at: "2024-08-08T16:51:07-05:00",
      updated_at: "2024-08-08T16:55:21-05:00",
      timestamp: "2024-08-08T20:30:30-05:00",
    },
    {
      id: 111444,
      api_model: "artworks",
      api_link: "https://api.artic.edu/api/v1/artworks/111444",
      is_boosted: false,
      title: "Retable of Saints Athanasius, Blaise, and Agatha",
      alt_titles: null,
      thumbnail: {
        lqip: "data:image/gif;base64,R0lGODlhBAAFAPQAAFtGL15KNlFIP19LOF5NPWlVP1hQR2hWRmtZRndkT25gVGVkYmhkYW5pZHBqZH1vYHt8fHx8fH6ChX+ChQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAAAAAAALAAAAAAEAAUAAAURINQ40XQg0jIEDAEUiSIYTwgAOw==",
        width: 12195,
        height: 16650,
        alt_text: "A work made of tempera on panel.",
      },
      main_reference_number: "1911.201",
      has_not_been_viewed_much: false,
      boost_rank: null,
      date_start: 1400,
      date_end: 1500,
      date_display: "1440/45",
      date_qualifier_title: "",
      date_qualifier_id: null,
      artist_display: "Master of Riglos (Spanish, active c. 1435–1460)",
      place_of_origin: "Spain",
      description: null,
      short_description: null,
      dimensions:
        "Christ on the Cross: 69.8 × 81.2 cm (27 1/2 × 32 in.); Coronation of the Virgin: 87.4 × 80.3 cm (34 7/16 × 31 5/8 in.); Scenes from the Life of Saint Blaise: 154.3 × 69.8 cm (60 3/4 × 27 1/2 in.); Saint Athanasius: 128.6 × 82 cm (50 11/16 × 32 5/16 in.); Scenes from the Life of Saint Agatha: 154.5 × 69.8 cm (60 7/8 × 27 1/2 in.)",
      dimensions_detail: [
        {
          depth: null,
          width: 81,
          height: 69,
          diameter: null,
          clarification: "Christ on the Cross",
        },
        {
          depth: null,
          width: 80,
          height: 87,
          diameter: null,
          clarification: "Coronation of the Virgin",
        },
        {
          depth: null,
          width: 69,
          height: 154,
          diameter: null,
          clarification: "Scenes from the Life of Saint Blaise",
        },
        {
          depth: null,
          width: 82,
          height: 128,
          diameter: null,
          clarification: "Saint Athanasius",
        },
        {
          depth: null,
          width: 69,
          height: 154,
          diameter: null,
          clarification: "Scenes from the Life of Saint Agatha",
        },
      ],
      medium_display: "Tempera on panel",
      inscriptions:
        "Inscribed: Do / min / e in foro / re tu / o ar / gua / s me (on Saint Athanasius’s book); Quicum / que v[u]l[t] / sal[v]us / es[s]e a[n] / te om / nia o[pus] (on the angel’s book at right); Sal.... (on the angel’s scroll\nat left)",
      credit_line: "Gift of the Antiquarian Society",
      catalogue_display: null,
      publication_history:
        "Year Book of the Antiquarian Society of the Art Institute of Chicago, Chicago, 1924, p. 35. \n\nChandler Rathfon Post, A History of Spanish Painting,, vol. 8, Cambridge, Mass.,  1941, pp. 378–80, fig. 169.\n\nJuan Antonio Gaya Nuño, La pintura española fuera de España, Madrid, 1958, p. 308, no. 2703. \n\nThe Art Institute of Chicago, Paintings in The Art Institute of Chicago: A Catalogue of the Picture Collection, 1961, p. 420. \n\nJosé Camón Aznar, Pintura medieval española, Summa artis 22, Madrid, 1966,\np. 474. \n\nJosé Gudiol, Pintura medieval en Aragón, Saragossa, 1971, p. 83, no. 273. \n\nJudith Berg Sobré, Behind the Altar Table: The Development of the Painted Retable in Spain, 1350–1500, Columbia, Mo., 1989, p. 52 n. 12.\n\nJudith Berg Sobré in Martha Wolff et al., Northern European and Spanish Paintings before 1600 in the Art Institute of Chicago, Chicago, 2008, pp. 92-95, ill.",
      exhibition_history: null,
      provenance_text:
        "Gift of the Antiquarian Society, 1911 [Registrar's records, Daybook, vol. 5, p. 8].",
      edition: null,
      publishing_verification_level: "Web Cataloged",
      internal_department_id: 14,
      fiscal_year: null,
      fiscal_year_deaccession: null,
      is_public_domain: true,
      is_zoomable: true,
      max_zoom_window_size: -1,
      copyright_notice: null,
      has_multimedia_resources: false,
      has_educational_resources: false,
      has_advanced_imaging: false,
      colorfulness: 0,
      color: {
        h: 182,
        l: 32,
        s: 7,
        percentage: 0.004843897668023988,
        population: 47,
      },
      latitude: null,
      longitude: null,
      latlon: null,
      is_on_view: false,
      on_loan_display: null,
      gallery_title: null,
      gallery_id: null,
      nomisma_id: null,
      artwork_type_title: "Painting",
      artwork_type_id: 1,
      department_title: "Painting and Sculpture of Europe",
      department_id: "PC-10",
      artist_id: 98435,
      artist_title: "Master of Riglos",
      alt_artist_ids: [],
      artist_ids: [98435],
      artist_titles: ["Master of Riglos"],
      category_ids: ["PC-10"],
      category_titles: ["Painting and Sculpture of Europe"],
      term_titles: [
        "painting",
        "saints",
        "15th century",
        "panel painting",
        "tempera",
        "women",
        "weapons",
        "Virgin Mary",
        "violence",
        "swords",
        "staffs",
        "spears",
        "religious scenes",
        "religious figures",
        "religious attire",
        "religious",
        "religion",
        "red (color)",
        "prayer",
        "people",
        "Mourning",
        "men",
        "martyrs",
        "Jesus",
        "interior",
        "horses",
        "horse",
        "gold (color)",
        "funerals",
        "figures",
        "dogs",
        "dog",
        "Devotion",
        "death",
        "crucifixions",
        "crowns",
        "cross",
        "coronations",
        "Christianity",
        "Christian subjects",
        "children",
        "cave",
        "book",
        "black (color)",
        "birds",
        "bird",
        "biblical",
        "bibles",
        "babies",
        "animals",
        "angels",
        "altar",
        "woodworking",
        "painting techniques",
        "painting (image making)",
        "painting",
        "wood (plant material)",
        "plant material",
        "panel (wood)",
        "organic material",
        "spanish",
        "altar",
        "altarpiece",
        "paint",
        "tempera",
        "european painting",
      ],
      style_id: "TM-14074",
      style_title: "15th century",
      alt_style_ids: [],
      style_ids: ["TM-14074"],
      style_titles: ["15th century"],
      classification_id: "TM-9",
      classification_title: "painting",
      alt_classification_ids: [
        "TM-15664",
        "TM-12858",
        "TM-1050",
        "TM-10387",
        "TM-153",
        "TM-54",
      ],
      classification_ids: [
        "TM-9",
        "TM-15664",
        "TM-12858",
        "TM-1050",
        "TM-10387",
        "TM-153",
        "TM-54",
      ],
      classification_titles: [
        "painting",
        "spanish",
        "altar",
        "altarpiece",
        "paint",
        "tempera",
        "european painting",
      ],
      subject_id: "TM-8827",
      alt_subject_ids: [
        "TM-8735",
        "TM-12304",
        "TM-8808",
        "TM-12307",
        "TM-8884",
        "TM-13634",
        "TM-12636",
        "TM-10125",
        "TM-12554",
        "TM-12732",
        "TM-14384",
        "TM-11421",
        "TM-11851",
        "TM-14073",
        "TM-8810",
        "TM-15520",
        "TM-10121",
        "TM-9204",
        "TM-12446",
        "TM-14037",
        "TM-8804",
        "TM-14272",
        "TM-11859",
        "TM-13472",
        "TM-15161",
        "TM-8865",
        "TM-14335",
        "TM-14366",
        "TM-12097",
        "TM-8870",
        "TM-8778",
        "TM-14892",
        "TM-12526",
        "TM-12372",
        "TM-8767",
        "TM-10118",
        "TM-15057",
        "TM-14696",
        "TM-11845",
        "TM-11211",
        "TM-13572",
        "TM-12337",
        "TM-12845",
        "TM-12354",
        "TM-12218",
        "TM-12268",
        "TM-12082",
      ],
      subject_ids: [
        "TM-8827",
        "TM-8735",
        "TM-12304",
        "TM-8808",
        "TM-12307",
        "TM-8884",
        "TM-13634",
        "TM-12636",
        "TM-10125",
        "TM-12554",
        "TM-12732",
        "TM-14384",
        "TM-11421",
        "TM-11851",
        "TM-14073",
        "TM-8810",
        "TM-15520",
        "TM-10121",
        "TM-9204",
        "TM-12446",
        "TM-14037",
        "TM-8804",
        "TM-14272",
        "TM-11859",
        "TM-13472",
        "TM-15161",
        "TM-8865",
        "TM-14335",
        "TM-14366",
        "TM-12097",
        "TM-8870",
        "TM-8778",
        "TM-14892",
        "TM-12526",
        "TM-12372",
        "TM-8767",
        "TM-10118",
        "TM-15057",
        "TM-14696",
        "TM-11845",
        "TM-11211",
        "TM-13572",
        "TM-12337",
        "TM-12845",
        "TM-12354",
        "TM-12218",
        "TM-12268",
        "TM-12082",
      ],
      subject_titles: [
        "saints",
        "women",
        "weapons",
        "Virgin Mary",
        "violence",
        "swords",
        "staffs",
        "spears",
        "religious scenes",
        "religious figures",
        "religious attire",
        "religious",
        "religion",
        "red (color)",
        "prayer",
        "people",
        "Mourning",
        "men",
        "martyrs",
        "Jesus",
        "interior",
        "horses",
        "horse",
        "gold (color)",
        "funerals",
        "figures",
        "dogs",
        "dog",
        "Devotion",
        "death",
        "crucifixions",
        "crowns",
        "cross",
        "coronations",
        "Christianity",
        "Christian subjects",
        "children",
        "cave",
        "book",
        "black (color)",
        "birds",
        "bird",
        "biblical",
        "bibles",
        "babies",
        "animals",
        "angels",
        "altar",
      ],
      material_id: "TM-2405",
      alt_material_ids: ["TM-2431", "TM-3478", "TM-3644", "TM-2601"],
      material_ids: ["TM-2405", "TM-2431", "TM-3478", "TM-3644", "TM-2601"],
      material_titles: [
        "tempera",
        "wood (plant material)",
        "plant material",
        "panel (wood)",
        "organic material",
      ],
      technique_id: "TM-3975",
      alt_technique_ids: ["TM-4248", "TM-3971", "TM-3891", "TM-14210"],
      technique_ids: ["TM-3975", "TM-4248", "TM-3971", "TM-3891", "TM-14210"],
      technique_titles: [
        "panel painting",
        "woodworking",
        "painting techniques",
        "painting (image making)",
        "painting",
      ],
      theme_titles: [],
      image_id: "f67ea925-dddf-0bf5-50af-fa9557b849ef",
      alt_image_ids: [],
      document_ids: [],
      sound_ids: [],
      video_ids: [],
      text_ids: [],
      section_ids: [],
      section_titles: [],
      site_ids: [],
      suggest_autocomplete_all: [
        {
          input: ["1911.201"],
          contexts: {
            groupings: ["accession"],
          },
        },
        {
          input: ["Retable of Saints Athanasius, Blaise, and Agatha"],
          weight: 769,
          contexts: {
            groupings: ["title"],
          },
        },
      ],
      source_updated_at: "2024-08-08T16:48:16-05:00",
      updated_at: "2024-08-08T16:50:20-05:00",
      timestamp: "2024-08-08T20:30:31-05:00",
    },
  ],
  info: {
    license_text:
      "The `description` field in this response is licensed under a Creative Commons Attribution 4.0 Generic License (CC-By) and the Terms and Conditions of artic.edu. All other data in this response is licensed under a Creative Commons Zero (CC0) 1.0 designation and the Terms and Conditions of artic.edu.",
    license_links: [
      "https://creativecommons.org/publicdomain/zero/1.0/",
      "https://www.artic.edu/terms",
    ],
    version: "1.10",
  },
  config: {
    iiif_url: "https://www.artic.edu/iiif/2",
    website_url: "http://www.artic.edu",
  },
};

const queryClient = new QueryClient();

describe("Agents", () => {
  it("should gallery artworks", async () => {
    render(
      <QueryClientProvider client={queryClient}>
        <AgentDetail />
      </QueryClientProvider>
    );
    const gallery = screen.getByText(/Artworks related/i);
    expect(gallery).toBeInTheDocument();
  });
});
